services:
  bitcoin:
    image: bitcoin/bitcoin
    container_name: bitcoin-regtest
    command: 
      - bitcoind
      - -regtest
      - -server=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=user
      - -rpcpassword=pass
      - -txindex=1
      - -printtoconsole
    volumes:
      - ./bitcoin-data:/root/.bitcoin
    ports:
      - "18443:18443"
      - "18444:18444"
    networks:
      - bitcoin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "getblockchaininfo"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: block-simulator
    depends_on:
      bitcoin:
      condition: service_healthy
    networks:
      - bitcoin-network
    environment:
      - BITCOIN_RPC_HOST=bitcoin
      - BITCOIN_RPC_PORT=18443
      - BITCOIN_RPC_USER=user
      - BITCOIN_RPC_PASSWORD=pass
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: bitcoin-explorer-api
    ports:
      - "8000:8000"
    depends_on:
      - bitcoin
    networks:
      - bitcoin-network
    environment:
      - BITCOIN_RPC_HOST=bitcoin
      - BITCOIN_RPC_PORT=18443
      - BITCOIN_RPC_USER=user
      - BITCOIN_RPC_PASSWORD=pass
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bitcoin-network:
    driver: bridge